import { Poppins } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";

const poppins = Poppins({
  weight: ["400", "600", "700", "800"],
  subsets: ['latin'],
})

export const metadata = {
  title: "CRUD App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <div className="w-full max-w-4xl m-auto p-4 min-h-screen flex flex-col">
        <Navbar />
        {children}
        </div>
      </body>
    </html>
  );
}
